# Copyright (c) 2020-2025 Siddharth Chandrasekaran <sidcha.dev@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: make check
      run: make check_utils
